### ISSUE TITLE
Question on differences with NestJS

### ISSUE THREAD

**Issue by zackarychapple** [calidan-x/summer#3]
Hello!  I discovered summer because of one of my friends @lilugirl starring it the other day.  I was curious how this project is different from [Nest](https://github.com/nestjs/nest). This project seems to follow a lot of the same conventions that @kamilmysliwiec does.

**Comment by calidan-x** [comment]
Hi, @zackarychapple, I am happy you post the first the first issue, sorry for late reply.

You can read the intro page in https://summerjs.dev/docs/intro.

In shorts, 
Summer is smaller.
Summer is more similar to Spring Boot while NestJS is similar to Angular. 
Summer does not has module, in fact, Summer try to simplify complex concepts and api to make it easy learning, coding and deployment.
Most Summer's modules, like core, request validation are self-writing while NestJS may base on express or other libraries.

**Comment by zackarychapple** [comment]
Thank you for the breakdown, I appreciate you drawing the distinction. Thank you for your time.
